Section A — Output Prediction

Q1. Array Operations and Vectorization

In [ ]:
import numpy as np
import pandas as pd

arr = np.array([10, 20, 30])
s = pd.Series([10, 20, 30])

print(arr * 2)
print(s * 2)

Similarity: Both perform element-wise multiplication by 2.


Difference: NumPy array displays only values, while a Pandas Series displays values along with an index.

Q2. Boolean Filtering



In [2]:
import pandas as pd
df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Marks': [45, 80, 65, 90]
})

result = df[df['Marks'] >= 65]

print(result[['Student', 'Marks']])

  Student  Marks
1       B     80
2       C     65
3       D     90


Rows: 3
Columns: 2

The condition Marks >= 65 selects students B, C, and D.

Q3. Descriptive Statistics

In [3]:
df = pd.DataFrame({
    'Marks': [10, 20, 30, 40, 50]
})

print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].median())

30.0
50
30.0


Q4. Group-wise Analysis

In [4]:
df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [40000, 30000, 60000, 50000]
})

print(df.groupby('Department')['Salary'].mean())

Department
HR    40000.0
IT    50000.0
Name: Salary, dtype: float64


groupby('Department') groups employees according to department, and mean() calculates the average salary for each department.

Q5. Pandas Correlation — Positive

In [7]:
df = pd.DataFrame({
    'Price': [10, 20, 30, 40],
    'Demand': [100, 80, 60, 40]
})

print(df['Price'].corr(df['Demand']))

-1.0


The correlation is -1, indicating a perfect negative relationship. As price increases, demand decreases.



Section B — Code Correction

Q1. Reading CSV with Header

Question:

The CSV already contains a header, but the code uses header=None.

In [2]:
import pandas as pd
df = pd.read_csv("students.csv")
print(df)

    ID     Name        Date  Marks
0  101  Asha, R  2026-09-01   80.0
1  102     Ravi  01/09/2026    NaN
2  103     Neha  2026-09-03    NaN


Q2. Five Highest Salaries


Question:

The objective is to display the five highest marks.

In [7]:
print(df.sort_values('Marks', ascending=False).head(5))

    ID     Name        Date  Marks
0  101  Asha, R  2026-09-01   80.0
1  102     Ravi  01/09/2026    NaN
2  103     Neha  2026-09-03    NaN


ascending=False sorts salaries from highest to lowest, and head(5) selects the first five records.


Q3. Cleaning Missing Data


Question:

The missing mark should be replaced by the column mean.

In [8]:
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
print(df)

    ID     Name        Date  Marks
0  101  Asha, R  2026-09-01   80.0
1  102     Ravi  01/09/2026   80.0
2  103     Neha  2026-09-03   80.0


fillna() returns a modified Series, so it must be assigned back to the column.

Q4. Correlation

Question:
Calculate the correlation between ID and Marks.

In [11]:
print(df['ID'].corr(df['Marks']))

nan


c:\Users\Jahnavi Gandhani\Desktop\calibo note book\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3036: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
c:\Users\Jahnavi Gandhani\Desktop\calibo note book\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3037: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]


Series.corr() directly calculates the correlation between two Series.

Section C — Edge Cases

Q1. NumPy Broadcasting


Question:

Arrays have shapes (3,1) and (1,3).

In [13]:
import numpy as np
a = np.array([[10], [20], [30]])
b = np.array([[1, 2, 3]])

result = a + b

print(result)
print(result.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)


NumPy broadcasting expands the (3,1) and (1,3) arrays to compatible (3,3) shapes.

If:

In [15]:
b = np.array([1, 2])
print(b)

[1 2]


then the shapes (3,1) and (2,) are not compatible for broadcasting, so NumPy raises a ValueError.

Q2. CSV Parsing, Missing Values and Dates

Question:

The CSV contains "Asha, R", missing marks, and dates in different formats.


Answer:

The comma inside "Asha, R" is handled correctly because the name is enclosed in double quotes. Pandas treats it as one field.

Potential issues:

Dates have different formats.
Marks contains missing values.
"NA" may represent a missing value, but this should be confirmed from the dataset's meaning.

In [16]:
df = pd.read_csv("students.csv")

df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")

df["Date"] = pd.to_datetime(
    df["Date"],
    errors="coerce",
    dayfirst=False
)

print(df)
print(df.dtypes)

    ID     Name       Date  Marks
0  101  Asha, R 2026-09-01   80.0
1  102     Ravi        NaT    NaN
2  103     Neha 2026-09-03    NaN
ID                int64
Name                str
Date     datetime64[us]
Marks           float64
dtype: object


errors="coerce" converts invalid values into NaN for numeric data and NaT for invalid dates.

"NA" should be investigated because it might mean a missing value, or it might have another meaning such as a special status.

Q3. Extreme Salary Value

In [21]:
highest = df.loc[df["Salary"].idxmax()]
print(highest)

Employee           D
Salary      10000000
Name: 3, dtype: object


Section D — Scenario-Based Question
Q1. Student Assessment Dataset

Question:
The dataset contains:

Missing marks
Duplicate records
IT, it, I.T.
Finance, finance
Marks stored as text
Absent
NA
88 marks
A mark of 105

Step 1 — Load and inspect

In [24]:
import pandas as pd

df = pd.read_csv("student_assessment_dirty.csv")

print(df.head())
df.info()
print(df.isnull().sum())

  Student_ID Student_Name Department Assessment   Marks
0       S101         Asha         IT     Python      85
1       S102         Ravi         it     Python      78
2       S103         Neha       I.T.     Python      92
3       S104        Karan         HR     Python     NaN
4       S105        Meera         HR     Python  Absent
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    15 non-null     str  
 1   Student_Name  15 non-null     str  
 2   Department    15 non-null     str  
 3   Assessment    15 non-null     str  
 4   Marks         12 non-null     str  
dtypes: str(5)
memory usage: 732.0 bytes
Student_ID      0
Student_Name    0
Department      0
Assessment      0
Marks           3
dtype: int64


Step 2 — Standardize departments

In [26]:
df["Department"] = (
    df["Department"]
    .str.strip()
    .str.upper()
    .str.replace(".", "", regex=False)
)
print(df)

   Student_ID Student_Name Department Assessment     Marks
0        S101         Asha         IT     Python        85
1        S102         Ravi         IT     Python        78
2        S103         Neha         IT     Python        92
3        S104        Karan         HR     Python       NaN
4        S105        Meera         HR     Python    Absent
5        S106        Arjun    FINANCE     Python         0
6        S107        Priya    FINANCE     Python        67
7        S108        Rahul         IT     Python        75
8        S102         Ravi         IT     Python        78
9        S109        Sneha         IT     Python       NaN
10       S110        Varun         HR     Python  88 marks
11       S111         Diya    FINANCE     Python        91
12       S112         Aman         IT     Python       NaN
13       S113        Nisha         HR     Python        64
14       S114        Kabir    FINANCE     Python       105


Step 3 — Remove duplicate records

In [28]:
df = df.drop_duplicates()
print(df)

   Student_ID Student_Name Department Assessment     Marks
0        S101         Asha         IT     Python        85
1        S102         Ravi         IT     Python        78
2        S103         Neha         IT     Python        92
3        S104        Karan         HR     Python       NaN
4        S105        Meera         HR     Python    Absent
5        S106        Arjun    FINANCE     Python         0
6        S107        Priya    FINANCE     Python        67
7        S108        Rahul         IT     Python        75
9        S109        Sneha         IT     Python       NaN
10       S110        Varun         HR     Python  88 marks
11       S111         Diya    FINANCE     Python        91
12       S112         Aman         IT     Python       NaN
13       S113        Nisha         HR     Python        64
14       S114        Kabir    FINANCE     Python       105


Step 4 — Convert Marks to numeric

In [30]:
df["Marks"] = (
    df["Marks"]
    .astype("string")
    .str.extract(r"(\d+\.?\d*)", expand=False)
)

df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")
print(df)

   Student_ID Student_Name Department Assessment  Marks
0        S101         Asha         IT     Python     85
1        S102         Ravi         IT     Python     78
2        S103         Neha         IT     Python     92
3        S104        Karan         HR     Python   <NA>
4        S105        Meera         HR     Python   <NA>
5        S106        Arjun    FINANCE     Python      0
6        S107        Priya    FINANCE     Python     67
7        S108        Rahul         IT     Python     75
9        S109        Sneha         IT     Python   <NA>
10       S110        Varun         HR     Python     88
11       S111         Diya    FINANCE     Python     91
12       S112         Aman         IT     Python   <NA>
13       S113        Nisha         HR     Python     64
14       S114        Kabir    FINANCE     Python    105


Step 5 — Investigate missing marks

In [31]:
print(df[df["Marks"].isna()])

   Student_ID Student_Name Department Assessment  Marks
3        S104        Karan         HR     Python   <NA>
4        S105        Meera         HR     Python   <NA>
9        S109        Sneha         IT     Python   <NA>
12       S112         Aman         IT     Python   <NA>


Step 6 — Identify invalid marks

In [32]:
invalid_marks = df[(df["Marks"] < 0) | (df["Marks"] > 100)]

print(invalid_marks)

   Student_ID Student_Name Department Assessment  Marks
14       S114        Kabir    FINANCE     Python    105


Step 7 — Display cleaned data

In [33]:
print(df)

   Student_ID Student_Name Department Assessment  Marks
0        S101         Asha         IT     Python     85
1        S102         Ravi         IT     Python     78
2        S103         Neha         IT     Python     92
3        S104        Karan         HR     Python   <NA>
4        S105        Meera         HR     Python   <NA>
5        S106        Arjun    FINANCE     Python      0
6        S107        Priya    FINANCE     Python     67
7        S108        Rahul         IT     Python     75
9        S109        Sneha         IT     Python   <NA>
10       S110        Varun         HR     Python     88
11       S111         Diya    FINANCE     Python     91
12       S112         Aman         IT     Python   <NA>
13       S113        Nisha         HR     Python     64
14       S114        Kabir    FINANCE     Python    105
