Section A – Conceptual Understanding      



A1. NumPy arrays vs Python lists

NumPy arrays are preferred for numerical computation because they are faster and use memory more efficiently. They support vectorized operations, so calculations can be performed on many values at once without writing Python loops. NumPy also provides many mathematical and statistical functions useful in AI/ML.

A2. Vectorization

Vectorization means performing operations on an entire NumPy array at once instead of processing each element using a Python loop. It is important for large datasets because NumPy operations are optimized and generally execute much faster than explicit Python loops.

A3. A * B vs A @ B

A * B performs element-wise multiplication, where corresponding elements are multiplied. It can be used when applying element-wise operations to neural-network data.

A @ B performs matrix multiplication. It is commonly used in neural networks to multiply an input/feature matrix by a weight matrix.

A4. Broadcasting

Broadcasting allows NumPy to perform element-wise operations on arrays with different shapes. Starting from the last dimension, the dimensions are compatible when they are equal or when one of them is 1. Missing dimensions are treated as 1.

A5. flatten() vs ravel()

flatten() returns a flattened copy of the array, while ravel() usually returns a view when possible. A view can use less additional memory. Therefore, for memory-constrained large-image processing, ravel() is generally preferred when modifying the flattened result is not required.

A6. axis=0 and axis=1

For:

In [2]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


axis=0 operates down the rows:

In [3]:
np.sum(a, axis=0)
# [5 7 9]

array([5, 7, 9])

axis=1 operates across the columns of each row:

In [4]:
np.sum(a, axis=1)
# [ 6 15]

array([ 6, 15])

A7. Normalization vs standardization

Scaling features is important because features with very different numerical ranges can affect ML models unevenly. Normalization commonly converts values to a fixed range such as [0, 1]. Standardization transforms values so that they have approximately mean 0 and standard deviation 1.

A8. np.nanmean()

np.nanmean() calculates the mean while ignoring NaN values. If np.mean() is used on an array containing NaN, the result will normally be NaN.

A9. RGB image shape

For ML data, the convention is:

(samples, features)

For RGB images, the equivalent batch representation is commonly:

(samples, height, width, channels)

For 64 RGB images of size 128 × 128:

(64, 128, 128, 3)

A10. Reproducibility

Reproducibility allows the same experiment to produce the same random values when repeated. Using a fixed seed makes debugging and comparing experiments easier.

In [7]:
rng = np.random.default_rng(42)
print(rng)

Generator(PCG64)


Section B – Predict the Output


B1

In [8]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

print((a + b).shape)

(3, 3)


B2

In [9]:
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])

[2 5]


B3

In [10]:
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])

[10 20]


B4


In [11]:
m = np.array([[1, 2],
              [3, 4]])

print(m.T @ m)

[[10 14]
 [14 20]]


B5

In [12]:
data = np.array([1, 2, np.nan, 4])
print(np.mean(data), np.nanmean(data))

nan 2.3333333333333335


B6

In [13]:
x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)

[0 1 1]


B7

In [14]:
a = np.zeros((3, 4))
print(a.ndim, a.size)

2 12


B8

In [15]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr[::-1, ::-1])

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


Section C – Coding / Implementation


C1

In [16]:
import numpy as np

scores = np.array([35, 45, 67, 28, 90, 39])

labels = np.where(scores >= 40, 'P', 'F')

print(labels)

['F' 'P' 'P' 'F' 'P' 'F']


C2

In [17]:
import numpy as np

def standardize(x):
    return (x - np.mean(x)) / np.std(x)

x = np.array([10, 20, 30, 40, 50])

result = standardize(x)

print(result)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


C3

In [18]:
import numpy as np

batch1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

batch2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

combined = np.vstack((batch1, batch2))

print(combined)
print(combined.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


C4

In [19]:
import numpy as np

X = np.random.default_rng(42).normal(size=(100, 5))

mean = X.mean(axis=0)
std = X.std(axis=0)

X_standardized = (X - mean) / std

print(X_standardized.shape)

(100, 5)


C5

In [20]:
import numpy as np

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])
b = 2.0

y_true = np.array([4, 6, 8])

y_pred = X @ w + b

mse = np.mean((y_true - y_pred) ** 2)

print("Predictions:", y_pred)
print("MSE:", mse)

Predictions: [4.5 6.  7.5]
MSE: 0.16666666666666666


C6

In [21]:
import numpy as np

rng1 = np.random.default_rng(42)
samples1 = rng1.normal(size=(10, 3))

rng2 = np.random.default_rng(42)
samples2 = rng2.normal(size=(10, 3))

print(samples1.shape)
print(np.array_equal(samples1, samples2))

(10, 3)
True


C7

In [22]:
import numpy as np

image = np.array([[0, 50, 100],
                  [150, 200, 255]])

normalized = (image - image.min()) / (image.max() - image.min())

print(normalized)

[[0.         0.19607843 0.39215686]
 [0.58823529 0.78431373 1.        ]]


C8

In [23]:
import numpy as np

images = np.random.default_rng(42).integers(
    0, 256, size=(4, 28, 28, 3)
)

average = images.mean(axis=(1, 2, 3))

print(average.shape)
print(average)

(4,)
[127.56505102 126.25212585 125.75722789 126.9914966 ]


Section D – Applied Problems


D1. Data Preprocessing Pipeline

Steps

Detect missing values using np.isnan().
Calculate an appropriate replacement value, such as the mean.
Replace missing values using np.where().
Standardize the cleaned data.
Feed the resulting clean numerical data into the model.

In [24]:
import numpy as np

data = np.array([
    [10.0, 20.0],
    [15.0, np.nan],
    [20.0, 30.0],
    [25.0, 35.0]
])

# Detect missing values
print("Missing values:")
print(np.isnan(data))

# Column means ignoring NaN
column_means = np.nanmean(data, axis=0)

# Replace NaN values
clean_data = np.where(
    np.isnan(data),
    column_means,
    data
)

# Standardize column-wise
mean = clean_data.mean(axis=0)
std = clean_data.std(axis=0)

standardized_data = (clean_data - mean) / std

print("Clean data:")
print(clean_data)

print("Standardized data:")
print(standardized_data)

Missing values:
[[False False]
 [False  True]
 [False False]
 [False False]]
Clean data:
[[10.         20.        ]
 [15.         28.33333333]
 [20.         30.        ]
 [25.         35.        ]]
Standardized data:
[[-1.34164079 -1.5430335 ]
 [-0.4472136   0.        ]
 [ 0.4472136   0.3086067 ]
 [ 1.34164079  1.2344268 ]]


D2. Image Batch Understanding

A single RGB image has the shape:

(height, width, channels)

For a 64 × 64 RGB image:

(64, 64, 3)

A batch of 16 RGB images has the shape:

(16, 64, 64, 3)


In [25]:
import numpy as np

rng = np.random.default_rng(42)

images = rng.integers(
    0, 256,
    size=(16, 64, 64, 3)
)

print("Batch shape:", images.shape)

average_image = images.mean(axis=0)

print("Average image shape:", average_image.shape)

Batch shape: (16, 64, 64, 3)
Average image shape: (64, 64, 3)


D3. Debug the Model Code

In [28]:
import numpy as np

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])
b = 2.0

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean((y_true - y_pred) ** 2)

print("Predictions:", y_pred)
print("MSE:", mse)

Predictions: [4.5 6.  7.5]
MSE: 244.16666666666666


Section E – Bonus


E1. Per-Column Min-Max Normalization

In [29]:
import numpy as np

X = np.array([
    [10, 100, 1000],
    [20, 200, 2000],
    [30, 300, 3000]
])

column_min = X.min(axis=0)
column_max = X.max(axis=0)

normalized = (X - column_min) / (column_max - column_min)

print(normalized)

[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


E2. Three-Level Score Classification

In [30]:
import numpy as np

scores = np.array([25, 40, 55, 70, 85, 95])

result = np.where(
    scores < 40,
    "Fail",
    np.where(scores <= 70, "Average", "Excellent")
)

print(result)

['Fail' 'Average' 'Average' 'Average' 'Excellent' 'Excellent']
